##
## Makefile for Norme (licence : Licence)
##
## Made by :   Ivad for group_name
## Mail :      ivanovic.ivad@gmail.com
##
## Started on Mon Feb 24 01:28:05 2014 by Ivad
## Updated on Mon Feb 24 01:28:05 2014 by Ivad
##

## Il faudra compiler avec un Makefile
## Il faudra utiliser les CFLAGS de compilation suivants : -Wall -Wextra -ansi -pedantic
## Pensez à enlever le mode debug
## Règle $(NAME), all, clean et mrproper
## Pensez au .PHONY
## N'oubliez pas de générer les .o
## Pas de wildcard
## Un Makefile principale qui compile tout à la racine du projet
